/**
 * Enum for tree actions
 */
export enum TreeActionEnum {
  COLLAPSE_ALL = 'COLLAPSE_ALL',
  EXPAND_ALL = 'EXPAND_ALL',
  HIERARCHICAL_ASSOCIATION = 'HIERARCHICAL_ASSOCIATION',
  HIERARCHICAL_INDEPENDENCE = 'HIERARCHICAL_INDEPENDENCE',
  SELECT_ALL = 'SELECT_ALL',
  UNSELECT_ALL = 'UNSELECT_ALL',
}
