/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./../components/AppLink/index.vue')['default']
    CommandPalette: typeof import('./../components/CommandPalette/index.vue')['default']
    IconSelect: typeof import('./../components/IconSelect/index.vue')['default']
    InputTag: typeof import('./../components/InputTag/index.vue')['default']
    LangSelect: typeof import('./../components/LangSelect/index.vue')['default']
    NoticeDropdown: typeof import('./../components/NoticeDropdown/index.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch/index.vue')['default']
    LayoutLogo: typeof import('./../layouts/components/LayoutLogo.vue')['default']
    LayoutMain: typeof import('./../layouts/components/LayoutMain.vue')['default']
    LayoutNavbar: typeof import('./../layouts/components/LayoutNavbar.vue')['default']
    LayoutSidebar: typeof import('./../layouts/components/LayoutSidebar.vue')['default']
    LayoutSidebarItem: typeof import('./../layouts/components/LayoutSidebarItem.vue')['default']
    LayoutTagsView: typeof import('./../layouts/components/LayoutTagsView.vue')['default']
    LayoutToolbar: typeof import('./../layouts/components/LayoutToolbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
